apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multicontainer
spec: 
  container:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
